### ISSUE TITLE
Improve Project Structure

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/ephemeris#1]
- [x] Implement a README.
- [x] Review and fix all Travis tests.
- [x] Generate and build documentation.
- [x] Setup a readthedocs site for this.
- [x] Write a couple tests.
- [x] Enable coverage testing, register with coveralls.

**Comment by jmchilton** [comment]
@bgruening took a huge step forward on this with #36. If we find a way to just dump the script help text to RST for readthedocs I think we are very close to having a decent, well-tested user-facing application here.

**Comment by rhpvorderman** [comment]
I'm working on a project that depends on tools in ephemeris. I am willing to look at the documentation if I am not duplicating effort and someone gives me directions as to where the readthedocs documentation is/should be stored.

**Comment by bgruening** [comment]
@rhpvorderman any documentation is welcome at this point and I don't think anyone is working on this yet. 
Thanks!

**Comment by jmchilton** [comment]
I'll set up a Sphinx outline and create a readthedocs today to enable contributions of documentation - thanks @rhpvorderman!

**Comment by jmchilton** [comment]
@rhpvorderman I have opened a PR for some initial Sphinx docs here (https://github.com/galaxyproject/ephemeris/pull/44). I think obvious wins are docstrings and improved command help - I'm pretty sure both of these kinds of documentation would be very valuable and both will ultimately land up on Sphinx or in users hands directly. Thanks so much for contributing - I'm looking forward to seeing what you are building!

**Comment by rhpvorderman** [comment]
> If we find a way to just dump the script help text to RST for readthedocs I think we are very close to having a decent, well-tested user-facing application here.

This is enabled in #46 . Using sphinx-argparse to write shed-install and run-data-manager's help texts to rst. It should be easily portable to other functions as well.

**Comment by rhpvorderman** [comment]
Coverage is now tested and reported. Some tests need to be converted to the new pytest format. But all in all. The project now has the desired structure.
