### ISSUE TITLE
shed-tools install not installing all dependencies

### ISSUE THREAD

**Issue by dwightkuo** [galaxyproject/ephemeris#101]
```shed-tools install -g http://127.0.0.1:8080/ -a 9da1b0b76e038a2a70e0649adb5205fa -t galaxy.yml --install_resolver_dependencies --latest --log_file logfile.txt```

>tools:
>\- name: tophat_fusion_post
>  owner: devteam
>  revisions:
>  \- f83394a2c2da
>  tool_panel_section_id: ngs_mapping
>  tool_panel_section_label: 'NGS: Mapping'
>  tool_shed_url: https://toolshed.g2.bx.psu.edu/

When I click on "Manage Tools", it shows "Installed, missing tool dependencies". When checking these, it seems many 'Installed repository dependencies' and 'Missing tool dependencies' have not been installed
![snapshot3](https://user-images.githubusercontent.com/22648143/42185533-159d904c-7dfe-11e8-9fe3-200317cee7fc.png)
. Is this an issue or am I misunderstanding how to use shed-tools?

**Comment by rhpvorderman** [comment]
This is an issue. 
Galaxy has two sorts of dependencies: Those that are installed using `conda` and those that are installed via the galaxy package management system. The latter are being phased out. The default behavior of `shed-tools` is therefore not to install tool-dependencies. Unfortunately this cannot be changed from the command line.

I will create a few commits in #104 to alleviate the issue.

**Comment by rhpvorderman** [comment]
This should be fixed with #104. 

Can you run ephemeris from the develop version?
- `git clone https://github.com/galaxyproject/ephemeris.git`
- Go to ephemeris directory
- `git checkout master`
- `git pull`
- `python setup.py install`

You are now running ephemeris development version. `shed-tools` should be available.
Can you install tool dependencies now?

**Comment by dwightkuo** [comment]
Yes, the development version fixes the issue!

**Comment by rhpvorderman** [comment]
I am happy to hear that. The next release of ephemeris will have these fixes incorporated. But until that time the development version should work fine.
