### ISSUE TITLE
shed-tools update doesn't update minor versions

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/ephemeris#111]
Hi,
Using ephemeris 0.9 to run `shed-tools update`, when a tool has a new minor version (ie new revision but same tool version number) I get something like this in the logs:

```
(1/597) Installing repository mothur_otu_association from iuc to section "NGS: Mothur" at revision 0fb08aeb215e (TRT: 0:00:01.740143)
	Repository mothur_otu_association is already installed.
	repository mothur_otu_association installed successfully (in 0:00:02.909464) at revision 0fb08aeb215e
```

And the tool doesn't get updated to the newest revision.
Is it the expected behavior?

**Comment by rhpvorderman** [comment]
No. It was a faulty model of checking whether the tool was installed that caused this.
The checking is now at revision level in the `dev` version.
Does this error still happen in the `dev` version?

**Comment by abretaud** [comment]
You mean the master branch? I've just tested with it and I still have the problem:
```
(767/1063) Installing repository mothur_otu_association from iuc to section "NGS: Mothur" at revision 0fb08aeb215e (TRT: 0:09:13.249862)
	Repository mothur_otu_association is already installed.
	repository mothur_otu_association installed successfully (in 0:00:02.851526) at revision 0fb08aeb215e
```

The latest revision [on the toolshed](https://toolshed.g2.bx.psu.edu/repository/view_changelog?id=c7e377b78e0e4e66) is 0fb08aeb215e, and my Galaxy instance has revisions 435b52e38889 and 12af8c375bb8 installed

**Comment by abretaud** [comment]
I've debugged a little this problem. So when this happens (ie a new revision but no change to the version):
- `shed-tools update` correctly detects the new revision and [calls the api](https://github.com/galaxyproject/ephemeris/blob/master/src/ephemeris/shed_tools.py#L158) to install the latest revision of the tool
- it goes through a few functions until reaching [`create_repository_dependency_objects`](https://github.com/galaxyproject/galaxy/blob/dev/lib/tool_shed/galaxy_install/repository_dependencies/repository_dependency_manager.py#L124)
- in this function, before launching the install, it calls [`repository_was_previously_installed`](https://github.com/galaxyproject/galaxy/blob/dev/lib/tool_shed/galaxy_install/repository_dependencies/repository_dependency_manager.py#L178)
- [`repository_was_previously_installed`](https://github.com/galaxyproject/galaxy/blob/dev/lib/tool_shed/util/repository_util.py#L889) says that the repository is already known, even if it's not the same revision
- the install is skipped because the known repository has status `installed`

Looking at [the comments](https://github.com/galaxyproject/galaxy/blob/dev/lib/tool_shed/util/repository_util.py#L892), it seems like the behavior of `repository_was_previously_installed` is intended.
I don't know exactly how this could be fixed without breaking everything.
Is the web UI using the same API when manually updating this kind of tool?

**Comment by bernt-matthias** [comment]
> Is the web UI using the same API when manually updating this kind of tool?

I don't know. 

And unfortunately I can't try if it has the same behaviour. When installing manually I get some problem with our proxy. I need to talk with our admins about this (but this will need time).

**Comment by bernt-matthias** [comment]
Forgot about my second instance (which is an the dev branch). I can confirm that Galaxy has the same behaviour when installing with the UI.

**Comment by rhpvorderman** [comment]
If this is a problem with the galaxy API we can unfortunately not fix it in ephemeris. Best to submit this as a bug to galaxy main I think.

**Comment by bernt-matthias** [comment]
https://github.com/galaxyproject/galaxy/issues/6698

**Comment by nsoranzo** [comment]
Fixed by https://github.com/galaxyproject/galaxy/pull/8815
