### ISSUE TITLE
Workaround needed: Repos that were updated without a version bump are not installable to the new revision

### ISSUE THREAD

**Issue by rhpvorderman** [galaxyproject/ephemeris#140]
See #https://github.com/galaxyproject/galaxy/issues/8243

**Comment by rhpvorderman** [comment]
I have taken a look at the "check if already installed code" and it is fairly inefficient. I can imagine it will also take quite long of you install thousands of tools. The checking algorithm is particularly slow. So that might need some work too. Unfortunately I have to leave office today at 11.30. But monday I will try and fix a few issues. Luckily we have plenty of testing in place so it should be possible to introduce a fix without introducing regressions.

**Comment by rhpvorderman** [comment]
@erasche. Can you give me one or more tools+revisions that refuse to update? That will give me some examples to work from. I will also check our own galaxy instance.

**Comment by erasche** [comment]
@mvdbeek reported in https://github.com/galaxyproject/galaxy/issues/8243#issuecomment-506479185 that iuc/fastqc tries repeatedly for version `e7b2202befea`.

I will have to look for others later., conference starts today.

**Comment by nsoranzo** [comment]
Fixed by https://github.com/galaxyproject/galaxy/pull/8815
