### ISSUE TITLE
run-datamanagers issue

### ISSUE THREAD

**Issue by anfie** [galaxyproject/ephemeris#157]
Hello guys, 
lately I wanted to test the run-datamangers script to together testconfig provided [here](https://github.com/galaxyproject/ephemeris/blob/master/tests/run_data_managers.yaml.test):

.venv/bin/python3.6 .venv/bin/run-data-managers -g http://galaxy-web.ipk-gatersleben.de -u fiebig@ipk-gatersleben.de -p password -a 123345abcd --config ephemeris/ephemeris/src/conf

Unfortunately, I failed right in the beginning:

<code> Storing log file in: /tmp/ephemeris_yor47xh6
Running data managers that populate the following source data tables: ['all_fasta']
data_manager_fetch_genome_all_fasta_dbkey already run for {'dbkey_source|dbkey_source_selector': 'new', 'dbkey_source|dbkey': 'RhinoVirusA', 'dbkey_source|dbkey_name': 'RhinoVirus A (NC_001617.1)', 'sequence_name': 'RhinoVirus A (NC_001617.1)', 'sequence_id': 'RhinoVirusA', 'reference_source|reference_source_selector': 'ncbi', 'reference_source|requested_identifier': 'NC_001617.1'}. Skipping.
</code>
**The skipping is fine, I managed to submit the first job via an API tester plugin meanwhile...so he jumped to second entry**
<code>
Traceback (most recent call last):
  File ".venv/bin/run-data-managers", line 8, in <module>
    sys.exit(main())
  File "/opt/galaxy/.venv/lib/python3.6/site-packages/ephemeris/run_data_managers.py", line 314, in main
    data_managers.run(log, args.ignore_errors, args.overwrite)
  File "/opt/galaxy/.venv/lib/python3.6/site-packages/ephemeris/run_data_managers.py", line 272, in run
    run_jobs(self.fetch_jobs, self.skipped_fetch_jobs)
  File "/opt/galaxy/.venv/lib/python3.6/site-packages/ephemeris/run_data_managers.py", line 258, in run_jobs
    (started_job['outputs'][0]['hid'], job["tool_id"], job["inputs"]))
</code>

I could not figure out what is the problem actually. The dict that is submitted as 'body' is fine. I got the correct answer, when using an API tester plugin (url: http://galaxy-web.ipk-gatersleben.de/api/tools?key=123345abcd, body and header: as provided in variable 'job' by ephemeris). 
But i never got it running with either bioblend functions or even with my own request (using pythons 'request' package'. I'm under the impression, that either the authentication failed or the body is not submitted correctly. Whatever I do, the only response I get is that to http://galaxy-web.ipk-gatersleben.de/api/tools, which is obviously not the required output.

Other stuff:
meris==0.10.5
"galaxy-web" is v19.09 (using an admin account)

I hope, the description is not too weird, but I'm totally new in this HTML request topic and after two day of testing, I'm also a bit frustrated about it. I would really prefer to use ephemeris for managing my references. Maybe anyone has idea, what went wrong?

Best regards (and stay healthy)
Anne

**Comment by anfie** [comment]
Ok, there must be a problem with our productive instance. Ephemeris is working fine in a complete new test instance of Galaxy. Sorry for that. Closed.

**Comment by bgruening** [comment]
@anfie maybe you production instance is really old?
