### ISSUE TITLE
Stripping the version from the tool_id (change in 0.10.7) breaks tool testing

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/ephemeris#179]
There is a change to shed-tools in ephemeris 0.10.7 that strips the version from the tool_id and passes a value `tool_id` to `verify_tool` that is actually the tool_id minus `/<tool_version>` https://github.com/galaxyproject/ephemeris/blob/master/src/ephemeris/shed_tools.py#L354

The GalaxyInteractorApi treats tool_id as a real tool_id with the version present, so calls to `test_data_download` will return test data for the most recent version of the tool regardless of which tool_version has been passed to verify_tool.

**Comment by mvdbeek** [comment]
That will be fixed once we release a new galaxy-tool-util package with https://github.com/galaxyproject/galaxy/pull/12539
