### ISSUE TITLE
New section creation is broken

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/ephemeris#186]
If the section is not already in `shed_tool_conf.xml`, it is not properly created, and tools are installed outside of a section. The install in galaxyproject/usegalaxy-tools#567 is an example.

The [`tools.yaml`](https://github.com/galaxyproject/usegalaxy-tools/blob/5398f4a856bbdace3ad552f068a4230693d613e2/cloud/datamash.yml.lock) contains `tool_panel_section_label` at the root both and `tool_panel_section_id` and `tool_panel_section_label` on each tool. The installation runs with:

```console
shed-tools install --skip_install_resolver_dependencies -v -g http://127.0.0.1:8080 -a deadbeef -t cloud/datamash.yml.lock
```

The resulting entries in `shed_tool_conf.xml` are:

```xml
    <tool file="toolshed.g2.bx.psu.edu/repos/iuc/datamash_reverse/f198773344e4/datamash_reverse/datamash-reverse.xml" guid="toolshed.g2.bx.psu.edu/repos/iuc/datamash_reverse/datamash_reverse/1.1.0+galaxy2">
        <tool_shed>toolshed.g2.bx.psu.edu</tool_shed>
        <repository_name>datamash_reverse</repository_name>
        <repository_owner>iuc</repository_owner>
        <installed_changeset_revision>f198773344e4</installed_changeset_revision>
        <id>toolshed.g2.bx.psu.edu/repos/iuc/datamash_reverse/datamash_reverse/1.1.0+galaxy2</id>
        <version>1.1.0+galaxy2</version>
    </tool>
    <tool file="toolshed.g2.bx.psu.edu/repos/iuc/datamash_transpose/ac092723240d/datamash_transpose/datamash-transpose.xml" guid="toolshed.g2.bx.psu.edu/repos/iuc/datamash_transpose/datamash_transpose/1.1.0+galaxy2">
        <tool_shed>toolshed.g2.bx.psu.edu</tool_shed>
        <repository_name>datamash_transpose</repository_name>
        <repository_owner>iuc</repository_owner>
        <installed_changeset_revision>ac092723240d</installed_changeset_revision>
        <id>toolshed.g2.bx.psu.edu/repos/iuc/datamash_transpose/datamash_transpose/1.1.0+galaxy2</id>
        <version>1.1.0+galaxy2</version>
    </tool>
    <tool file="toolshed.g2.bx.psu.edu/repos/iuc/datamash_ops/746e8e4bf929/datamash_ops/datamash-ops.xml" guid="toolshed.g2.bx.psu.edu/repos/iuc/datamash_ops/datamash_ops/1.1.0+galaxy2">
        <tool_shed>toolshed.g2.bx.psu.edu</tool_shed>
        <repository_name>datamash_ops</repository_name>
        <repository_owner>iuc</repository_owner>
        <installed_changeset_revision>746e8e4bf929</installed_changeset_revision>
        <id>toolshed.g2.bx.psu.edu/repos/iuc/datamash_ops/datamash_ops/1.1.0+galaxy2</id>
        <version>1.1.0+galaxy2</version>
    </tool>
```

**Comment by cat-bro** [comment]
This issue is with the api. `tool_panel_section_id` and `tool_panel_section_label` [cannot be used simulateously](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/tool_shed_repositories.py#L102) and if the bioblend function receives both arguments it will only send `tool_panel_section_id` https://github.com/galaxyproject/bioblend/blob/main/bioblend/galaxy/toolshed/__init__.py#L157.

Our workaround has been to only have `tool_panel_section_id` in the yaml files.

**Comment by natefoo** [comment]
Thanks! I wondered if this was the case. Do you just manually edit the label then after installation?

**Comment by cat-bro** [comment]
Oops - I meant that we only use label and not id in the yaml file, I have edited my comment above.

**Comment by natefoo** [comment]
IIRC the reason we started adding the ID was for synchronization between EU, AU, and US tool panel section IDs as discussed in galaxyproject/usegalaxy-tools#9. Although we haven't ended up using a common repo (and probably won't), I've been using the algorithm [in my comment here](https://github.com/galaxyproject/usegalaxy-tools/issues/9#issuecomment-500847395) to generate new IDs, and it'd be nice to keep that.

For example, @luke-c-sargent is adding a new section in galaxyproject/usegalaxy-tools#600 and we need to drop the section ID to avoid this bug, but then Galaxy will generate the ID. In this case it's fine - `QIIME2` will become `qiime2`, but it's a bigger issue with, for example a label like `FASTA/FASTQ`, which becomes `fasta/fastq`.

**Comment by mvdbeek** [comment]
Might be dense here, but I don't see how `I've updated the logic on the ephemeris side to only send the label if both are defined:` would be a problem, it should just work ?

**Comment by mvdbeek** [comment]
@natefoo Is the problem maybe that we just need to install from upstream pip ? https://github.com/galaxyproject/usegalaxy-tools/blob/master/.ci/jenkins.sh#L26

**Comment by natefoo** [comment]
Yes, the new section issue should be fixed (upstream), but with the ID being ignored now, the format for new section IDs won't be correct.
