### ISSUE TITLE
Requires Galaxy >16.04

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/ephemeris#22]
Not directly clear from the script, but older Galaxy versions will not include the tool revision and the `generate_tool_list_from_ga_workflow_files.py` and `get-tool-list` will silently produce empty files.
see https://github.com/galaxyproject/galaxy/pull/1752 and https://github.com/galaxyproject/galaxy/pull/1636

**Comment by mvdbeek** [comment]
16.04 should work, if it doesn't that would be a bug. I will add a check for the galaxy version.
