### ISSUE TITLE
Improve Release Process

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/ephemeris#31]
- [x] Document it. It is the same procedure as planemo but it isn't documented - https://github.com/galaxyproject/planemo/blob/master/docs/developing.rst.
- [x] Add others' to PyPI roles.

**Comment by rhpvorderman** [comment]
https://ephemeris.readthedocs.io/en/latest/developing.html documents it, and @bgruening also has PyPI permissions.

**Comment by jmchilton** [comment]
Thanks for closing this out!
