### ISSUE TITLE
Latest documentation not updated on readthedocs.

### ISSUE THREAD

**Issue by rhpvorderman** [galaxyproject/ephemeris#48]
Are webhooks configured? This will allow automatic updating of readthedocs as soon as the documentation is updated. Now the latest documentation changes are not visible on readthedocs.

**Comment by bgruening** [comment]
ping @jmchilton I do not have permission to configure anything.

**Comment by jmchilton** [comment]
Thanks for the ping @bgruening - yeah I triggered a rebuild and tried to enable a trigger - I don't remember having to set up that trigger before though - I guess we will see.

**Comment by rhpvorderman** [comment]
I checked and documentation now is automatically updated.
