### ISSUE TITLE
0.7.1 Release

### ISSUE THREAD

**Issue by rhpvorderman** [galaxyproject/ephemeris#61]
Run-data-managers has improved significantly, an error in galaxy-wait has been fixed an unbounded variable has been fixed. ( #53 #55 #57 )
@jmchilton could you release 0.7.1 so that these changes are made available to the public?
Also I believe we have fixed a lot of issues in #1 now. Maybe the issues in #31 can now also be addressed?
Thanks!

**Comment by bgruening** [comment]
@jmchilton I also got a few other PRs in. So if you can roll out a new version that would be fantastic.

**Comment by rhpvorderman** [comment]
Maybe we can also get #64 in.
Also, this release will break the `shed-install` command. It will use the `shed-tools install` command instead.
By the rules of [semantic version](https://semver.org/) we should move to a next major version. But since we are still on 0 that does not necessarily apply.
Since the package is already being used in production quite a lot I think a move to version 1.0.0 is warranted.
