### ISSUE TITLE
Shed-install should be able to update all the tools in a galaxy instance

### ISSUE THREAD

**Issue by rhpvorderman** [galaxyproject/ephemeris#63]
Would be nice for a cron job to keep all the tools up to date.
Changes could be made also fixing #62. 

Please let me know if this functionality is useful and I will fix this issue and #62.

I can't find a button in galaxy that just says: "update all  tools"

**Comment by afgane** [comment]
I'd love to see this added.

**Comment by erasche** [comment]
:+1:
