### ISSUE TITLE
shed-install verbose

### ISSUE THREAD

**Issue by selten** [galaxyproject/ephemeris#65]
The documentation (https://ephemeris.readthedocs.io/en/latest/commands/shed-install.html) states that verbose is an option, however when I tried it I got:

```
usage: usage: python shed-install <options>
shed-install: error: unrecognized arguments: -v=True
```

**Comment by rhpvorderman** [comment]
Verbose does not take any parameters just use:
`shed-install -v <other parameters>` for verbosity.
Did this solve your problem?

**Comment by rhpvorderman** [comment]
I see now that this was documented in the wrong way due to our automated documentation.
Made a pull request fixing this.
Thanks for reporting this @selten

**Comment by bgruening** [comment]
Thanks to @rhpvorderman this looks now better: http://ephemeris.readthedocs.io/en/latest/commands/shed-tools.html

@selten let us know if it is still confusing!
