### ISSUE TITLE
Enable coverage testing

### ISSUE THREAD

**Issue by rhpvorderman** [galaxyproject/ephemeris#71]
Last issue on the list #1.
We should enable coverage testing so we can make sure the entire ephemeris package is tested.
This may lead us to remove/deprecate functions that are untestable/unmaintainable for stability's sake. I feel it would improve our tests and our code base greatly.

**Comment by rhpvorderman** [comment]
Coverage integration is almost there. Two things need to happen

1. [ ] @jmchilton personal ephemeris codacy page should be replaced with the galaxyproject/ephemeris codacy page.
2 [ ] #106 needs to be pulled.

**Comment by rhpvorderman** [comment]
Coverage is now being integrated with ephemeris.

**Comment by jmchilton** [comment]
Thanks so much, this is amazing.
