### ISSUE TITLE
shed-install stores logs in a fixed tmp location.

### ISSUE THREAD

**Issue by rhpvorderman** [galaxyproject/ephemeris#84]
This is a problem when you run ephemeris as a different user on the same system:
`Permission denied: "/tmp/galaxy_tool_install.log"`
Since this is in /tmp you cannot delete the file of the other user.

**Comment by afgane** [comment]
I'm actually surprised this has remained in the code for this long... It's just a default: https://github.com/galaxyproject/ephemeris/blob/master/ephemeris/shed_tools.py#L738

I guess we should make it an optional command line parameter?

**Comment by rhpvorderman** [comment]
Also in [run-data-managers](https://github.com/galaxyproject/ephemeris/blob/master/ephemeris/run_data_managers.py#L284). 
I guess we should create a default random directory in tmp (functionality probably in python standard library) and indeed make an option that changes this from the command line.
Additionally we can add a log.info statement where the log is stored (citing full path) when the program is started.
