### ISSUE TITLE
Suggestion drop python 2 support and start using type hints.

### ISSUE THREAD

**Issue by rhpvorderman** [galaxyproject/ephemeris#92]
Python 3 was released in December 2008. It is now almost ten years later. Anyone who desperately wants to cling to python 2 is welcome to it. But I don't want to miss out on some nice functionality that python3 offers.
One of the things that would be a pleasure to use in ephemeris is type hinting. This allows the IDE to actually know what type of variable you are working with. It prevents a lot of mistakes and makes it easier to develop. Now I often have to look up the original function to check what is being done and see whether this variable is some random class, a list, string or something else. Also some stuff will be checked at compile time, catching errors before they occur. This will be very nice when integrating pytest #80 and refactoring shed-tools #91.
So I suggest we drop the python2 testing and focus our efforts on python3 for the coming releases. 
People who still need a python2 version of ephemeris: the releases up to 0.8.0 are still pretty solid and useful.

**Comment by jmchilton** [comment]
I get the desire, I really do but the Galaxy community is stuck in the past and I think we need to deal with that for another couple years at least. All of the VMs I use ephemeris with have Python 2 as the default Python, Galaxy itself depends on Python 2. I would like to someday include ephemeris in some form when you "pip install galaxy", that will depend on Python 2 support. Planemo depends on ephemeris as a library and will support Python 2 until at least 2020. I think ephemeris needs to continue to support Python 2 for the time being.

I have some experience with type annotations in mixed Python 2/3 projects - it is possible to annotate types with comments and use mypy to check the code (http://mypy.readthedocs.io/en/latest/python2.html). I doubt however the IDE support will be as good as with Python 3 only code - I'll admit that. I'm not defending Python 2, I'd rather be writing Python 3 only myself of course.

**Comment by mvdbeek** [comment]
That said we're making progress with galaxy and py3. I think having a decent test coverage will also uncover a lot of errors that type hinting might prevent us from doing.

**Comment by rhpvorderman** [comment]
> That said we're making progress with galaxy and py3. I think having a decent test coverage will also uncover a lot of errors that type hinting might prevent us from doing.

A lot but not all. But that is not my major attractor to type hinting. One of the major advantages of type hinting is that it makes development much easier. I also help in developing some scala tools here at the LUMC and the typing stuff makes it just so easy. I miss that  every time when I work on ephemeris.

> I get the desire, I really do but the Galaxy community is stuck in the past and I think we need to deal with that for another couple years at least. All of the VMs I use ephemeris with have Python 2 as the default Python, Galaxy itself depends on Python 2. I would like to someday include ephemeris in some form when you "pip install galaxy", that will depend on Python 2 support. Planemo depends on ephemeris as a library and will support Python 2 until at least 2020. I think ephemeris needs to continue to support Python 2 for the time being.

Maybe I phrased it too harshly. How about making a new release of ephemeris now? There is some very nice functionality added and some bugs have been fixed.  We can _support_ this release for python2. Fix bugs etcetera. But we will keep this on a separate branch. We will only develop new features and do cool stuff with the python3 branch. Doing the same thing for planemo is perhaps also possible.
The worst thing that can happen is that people who are stuck in the past, will be stuck in the past. But they wouldn't mind obviously ;-).

**Comment by jmchilton** [comment]
> We will only develop new features and do cool stuff with the python3 branch.

I think the rest of us are not with you on this, I have features I'd like to develop still and I'd like to develop them in a way that can be used with Planemo and Galaxy - both of which are going to support Python 2 for years still. If you want to have a Python 3 only branch - we can try to work on a way to support that or if you want to have subsets of the code that are Python 3 only I think that might be workable also. I think most other people contributing to ephemeris though will want their core contributions (even the enhancements) working with Python 2.

**Comment by rhpvorderman** [comment]
The thing is: ephemeris only interacts with galaxy via a json API. So it does not matter which python version galaxy uses. 
I started this issue because I still see a lot of improvements that can be made to ephemeris, and I do not want to use python2 unless it is strictly necessary. It is lot of legacy weight holding development back.
If python2 support is required for continued planemo and galaxy support that makes it strictly necessary.
For galaxy I don't see this (JSON api), but if you say it is needed for planemo, I am happy to continue with python2.

**Comment by bgruening** [comment]
Sorry, to be late here. @rhpvorderman you main intesterest is static typing? Why not use https://github.com/python/mypy also for our python2 code base for the time being? 

> The thing is: ephemeris only interacts with galaxy via a json API. So it does not matter which python version galaxy uses.

But this means that every time you want to have ephemeris you need to have a python3 env available, adding 300MB to everything. python2 tools that call ephemeris are not that easy to develop and so on ...

**Comment by rhpvorderman** [comment]
> Why not use https://github.com/python/mypy also for our python2 code base for the time being?

Because it I do not want to use third-party packages for the sole purpose of keeping python2 alive. Why add extra cruft if it is in the standard library of python 3?

> But this means that every time you want to have ephemeris you need to have a python3 env available, adding 300MB to everything. python2 tools that call ephemeris are not that easy to develop and so on ...

I agree. It seems we have to stick it out to the bitter end of python2.

**Comment by bgruening** [comment]
> Why add extra cruft if it is in the standard library of python 3?

Because you want to use it, and right so! But we also need to support python2 :)

**Comment by rhpvorderman** [comment]
Closing this issue. The reason for python 2 support is clear.
