### ISSUE TITLE
shed_tool_conf_cleaner.py

### ISSUE THREAD

**Issue by drosofff** [galaxyproject/ephemeris#94]
Hi everybody,

If you think that this script can be useful for Galaxy admin, I may push it in ephemeris. Tell me your thoughts.

https://github.com/ARTbio/tools-artbio/pull/284

**Comment by jmchilton** [comment]
I don't manage shed tool confs ever really, but this looks pretty awesome - thanks for the heads up! I would PR it against Galaxy's scripts/ directory instead of ephemeris to be honest - I've discussed this a bit here https://github.com/galaxyproject/ephemeris/pull/40#issuecomment-299865581.

**Comment by drosofff** [comment]
Thanks @jmchilton. Yes I'll do this, probably.

**Comment by rhpvorderman** [comment]
@drosofff can this issue be closed?

**Comment by rhpvorderman** [comment]
Closing because now reaction was received from topic starter.
